sudo: required

language: go

services:
  - docker

go:
  - "1.10.x"

cache:
  directories:
    - $HOME/.go


before_install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

install:
  - docker pull golang:1
  - cd terraform && terraform init && cd ..

script:
# Terraform Validation
  - cd terraform && terraform validate -var-file=../terraform.test.json && cd ..
# Run Go Unit Tests
  - docker run --rm -v "$HOME/.go":/go -v "$PWD/orchestration":/app -w /app golang:1 make test
# Build application
  - docker run --rm -v "$HOME/.go":/go -v "$PWD/orchestration":/app -w /app -e HOST_UID="$UID" golang:1 make
# Build docker image
  - docker build --pull -t openshift-aws .

notifications:
  email:
    on_success: never
    on_failure: change