---
- name: Add EBS Storage configuration
  hosts: localhost
  become: false
  tasks:
    - name: Login to Cluster
      command: oc login master.cc-openshift.de:8443 -u admin -p OriginAdmin --insecure-skip-tls-verify

    - name: Delete old EBS storage class
      command: oc delete storageclass gp2

    - name: Create EBS storage class
      command: oc apply -f ../generated/ebs.yml
