---
- name: Add EBS Storage configuration
  hosts: masters[0]
  become: true
  tasks:
    - name: Delete old EBS storage class
      command: oc delete storageclass gp2

    - name: Copy EBS storage class definition
      copy:
        src: ../generated/ebs.yml
        dest: /tmp/ebs.yml

    - name: Apply EBS storage class definition
      command: oc apply -f /tmp/ebs.yml

    - name: Remove temporary files
      file:
        state: absent
        path: /tmp/ebs.yml
