---
- name: Add EBS Storage configuration
  hosts: masters[0]
  become: true
  tasks:
    - name: Delete old EBS storage class
      oc:
        name: gp2
        state: absent
        kind: StorageClass

    - name: Create EBS storage class
      oc:
        state: present
        inline:
          kind: StorageClass
          apiVersion: storage.k8s.io/v1
          metadata:
            name: aws-ebs
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
          provisioner: kubernetes.io/aws-ebs
          parameters:
            type: gp2
            encrypted: "true"
            fsType: ext4
            zones: eu-central-1a, eu-central-1b, eu-central-1c
