---
- name: Configure nodes for NFS
  hosts: nodes
  become: true
  tasks:
    - name: Set SELinux value virt_use_nfs
      seboolean:
        name: virt_use_nfs
        state: yes
        persistent: yes

    - name: Set SELinux value virt_sandbox_use_nfs
      seboolean:
        name: virt_sandbox_use_nfs
        state: yes
        persistent: yes

    - name: Add firewalld Port 2049
      firewalld:
        port: 2049/tcp
        permanent: true
        state: enabled

    - name: Add firewalld Port 20048
      firewalld:
        port: 20048/tcp
        permanent: true
        state: enabled

    - name: Add firewalld Port 111
      firewalld:
        port: 111/tcp
        permanent: true
        state: enabled

    - name: Enable firewalld nfs service
      firewalld:
        service: nfs
        permanent: true
        state: enabled

    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted

- name: Add EFS Storage configuration
  hosts: localhost
  become: false
  tasks:
    - name: Login to Cluster
      command: oc login master.cc-openshift.de:8443 -u admin -p OriginAdmin --insecure-skip-tls-verify

    - name: Change Project to openshift-infra
      command: oc project openshift-infra

    - name: Create EFS roles
      command: oc apply -f static/efs-roles.yml

    - name: Apply policy hostmount-anyuid
      command: oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:openshift-infra:efs-provisioner

    - name: Apply policy anyuid
      command: oc adm policy add-scc-to-user anyuid system:serviceaccount:openshift-infra:efs-provisioner

    - name: Apply cluster ClusterRole
      command: oc adm policy add-cluster-role-to-user efs-provisioner-runner system:serviceaccount:openshift-infra:efs-provisioner

    - name: Create Persistence configuration
      command: oc apply -f ../generated/efs.yml
