---
- name: Configure nodes for NFS
  hosts: nodes
  become: true
  tasks:
    - name: Set SELinux value virt_use_nfs
      seboolean:
        name: virt_use_nfs
        state: yes
        persistent: yes

    - name: Set SELinux value virt_sandbox_use_nfs
      seboolean:
        name: virt_sandbox_use_nfs
        state: yes
        persistent: yes

    - name: Add firewalld Port 2049
      firewalld:
        port: 2049/tcp
        permanent: true
        state: enabled

    - name: Enable firewalld nfs service
      firewalld:
        service: nfs
        permanent: true
        state: enabled

    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted

- name: Add EFS Storage configuration
  hosts: masters[0]
  become: true
  tasks:
    - name: Copy EFS roles definition
      copy:
        src: static/efs-roles.yml
        dest: /tmp/efs-roles.yml

    - name: Copy EFS storage class definition
      copy:
        src: ../generated/efs.yml
        dest: /tmp/efs.yml

    - name: Change Project to openshift-infra
      command: oc project openshift-infra

    - name: Create EFS roles
      command: oc apply -f /tmp/efs-roles.yml

    - name: Apply policy hostmount-anyuid
      command: oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:openshift-infra:efs-provisioner

    - name: Apply policy anyuid
      command: oc adm policy add-scc-to-user anyuid system:serviceaccount:openshift-infra:efs-provisioner

    - name: Apply cluster ClusterRole
      command: oc adm policy add-cluster-role-to-user efs-provisioner-runner system:serviceaccount:openshift-infra:efs-provisioner

    - name: Create EFS storage class
      command: oc apply -f /tmp/efs.yml

    - name: Delete temporary files
      file:
        path: "/tmp/efs.yml"
        state: absent

    - name: Delete temporary files
      file:
        path: "/tmp/efs-roles.yml"
        state: absent